name: Build and publish Docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag, latest or same as npm build"
        required: true
        default: "v1.0.0"
        type: string

      build_tag:
        description: "Dist version, set this to the version being built in npm, e.g v1.0.0"
        required: false
        default: "v1.0.0"
        type: string

      node_version:
        description: "NPM version to build dist from"
        require: false
        type: choice
        default: "24.14.0"
        options:
        - "24.14.0"
        - "22.22.1"

      short_version:
        describe: "Build with short version paths in manifest and config"
        require: false
        type: boolean
        default: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Use Node.js ${{ inputs.node_version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ inputs.node_version }}

      - name: Clean
        run: |
          npm cache clean --force

      - name: Install
        run: |
          npm ci

      - name: Test
        run: |
          npm test

      - name: Build
        run: |
          npm run build -- --env shortVersion=${{ inputs.short_version }}

      - name: Log in to GHCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f #v4.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: lower-repo
        name: Repository to lowercase
        run: |
          echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a #v7.3.0
        with:
          context: .
          push: false
          tags: |
            ghcr.io/${{ steps.lower-repo.outputs.repository }}:${{ inputs.tag }}
            ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest
          build-args: |
            TAG=${{ inputs.build_tag }}