name: Unit Tests

on: [workflow_call] # yamllint disable-line rule:truthy

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.20.6, 20.18.2, 22.13.1]

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean
        run: |
          npm cache clean --force

      - name: Install
        run: |
          npm install

      - name: Test
        run: |
          npm test

      - name: Build
        run: |
          npm run build
