name: Unit Tests

on: [workflow_call] # yamllint disable-line rule:truthy

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.20.6, 20.18.2, 22.13.1]

    steps:
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean
        run: |
          npm cache clean --force

      - name: Install
        run: |
          npm install

      - name: Test
        run: |
          npm test

      - name: Build
        run: |
          npm run build
