name: Unit Tests

on: [workflow_call] # yamllint disable-line rule:truthy

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.20.6, 20.18.2, 22.13.1]

    steps:
      - uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean
        run: |
          npm cache clean --force

      - name: Install
        run: |
          npm install

      - name: Test
        run: |
          npm test

      - name: Build
        run: |
          npm run build
